CREATE TABLE games (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    teaser TEXT,
    description1Html TEXT,
    description2Html TEXT,
    description3Html TEXT,
    type VARCHAR(50),
    popularity DECIMAL(10,2),
    slug VARCHAR(255),
    favorite BOOLEAN,
    ageGroup INT,
    durationGroup INT,
    participantsGroup INT,
    image_path VARCHAR(255),
    thumbnail_path VARCHAR(255),
    video VARCHAR(255),
    area VARCHAR(50),
    extra_description2 TEXT,
    tips TEXT,
    materials TEXT,
    categories JSON,
    tags JSON,
    state INT,
    elo_rating INT DEFAULT 1200,
    matches_played INT DEFAULT 0
);
